cloud:
  aws:
    access-key-id: foo
    secret-access-key: bar
    dynamodb:
      endpoint: http://localhost:4566
log:
  config:
    path: ./logs
    filename: dev
    max-history: 7
    total-size-cap: 1GB